### ISSUE TITLE
Kleiner Fehler

### ISSUE THREAD

**Issue by Kakifrucht** [cbmainz/flarum-de#1]
Erstmal großes Dankeschön hierfür! Hoffe schon seit längerem das sich da jemand erbarmt den Support hierfür zu übernehmen ;)

Paar kleinere Fehler: composer.json Zeile 23 Tippfehler.
Im Dropdown, statt Letzter vielleicht 'Zuletzt' steht Neuster statt Neuester.
Im Dropdown, wenn man auf seinen Namen klickt, steht statt "Profil" Profile.
Im Kontoeinstellungsbildschirm steht "Andere dürden meinen Online-Status sehen".
Und ich finde bei den gefolgten Diskussionen nicht unbedingt Schlüssig, was mit "Folgen" gemeint sein soll. Da sollte man sich vielleicht etwas passenderes überlegen, zum beispiel "Verfolgte Diskussionen" oder ähnliches.

Und die Deutschland Flagge hat irgendwie ein komisches gelb ;)

**Comment by cbmainz** [comment]
Danke für die Rückmeldung. Die Rechtschreibfehler werde ich auf alle Fälle verbessern. 

Bei der Übersetzung zu "Folgen" werde ich noch mal nachdenken, aber vielleicht hat auch noch jemand andere Ideen. "Verfolgte Diskussionen" überzeugt mich auch noch nicht.

**Comment by Kakifrucht** [comment]
Ja ich bin davon auch nicht überzeugt, ich melde mich wenn ich eine Idee habe.

**Comment by cbmainz** [comment]
Gibt es ein offizielles Gelb für die Deutschlandfahne?

**Comment by Kakifrucht** [comment]
https://de.wikipedia.org/wiki/Flagge_Deutschlands

**Comment by cbmainz** [comment]
Habt auch gerade gefunden, danke.

**Comment by Kakifrucht** [comment]
Beim Dropdown zum schließen eines Threads steht "Geschlossen", das sollte vielleicht eher Schließen heißen ;)

**Comment by cbmainz** [comment]
So, habe es zumindest hier bei Github aktualisiert.

**Comment by Kakifrucht** [comment]
https://github.com/cbmainz/flarum-de/commit/534cdd9a53e52f6ad499fdd8f3e3644e240166d2#diff-fd1b8443415c3f3a058d04812d1e90edR116
Soweit ich das sehe ist das im Permissions Menü wenn die Forum Anmeldung deaktiviert ist, insofern war das schon richtig.
https://github.com/cbmainz/flarum-de/blob/master/locale/flarum-lock.yml#L23
Das ist wohl die richtige Zeile, die von Geschlossen zu schließen geändert werden sollte.

**Comment by Kakifrucht** [comment]
https://github.com/cbmainz/flarum-de/commit/534cdd9a53e52f6ad499fdd8f3e3644e240166d2#diff-fd1b8443415c3f3a058d04812d1e90edR225
Das erscheint mir auch nicht so sinnig, soweit ich weiß sortiert das ja dann nach Threads denen am meisten geantwortet wurde. Wobei Top auch suboptimal war.

**Comment by cbmainz** [comment]
Ah, stimmt.

**Comment by cbmainz** [comment]
Was meinst du hiermit? https://github.com/cbmainz/flarum-de/commit/534cdd9a53e52f6ad499fdd8f3e3644e240166d2#diff-fd1b8443415c3f3a058d04812d1e90edR225

**Comment by Kakifrucht** [comment]
Ist das nicht die Zeile die das hier umstellt? https://imgur.com/qx7MGtR

**Comment by cbmainz** [comment]
Doch, hatte mich verguckt. Habe es schon geändert: https://github.com/cbmainz/flarum-de/blob/master/locale/core.yml#L225

**Comment by Kakifrucht** [comment]
https://github.com/cbmainz/flarum-de/commit/c1136bf5186b1d63b8de21d54969a49569a9fde6#diff-f8aeda8cfe53a97c24b77a7dac48657cR23

**Comment by cbmainz** [comment]
Danke, das war sehr hilfreich, dass jemand noch mal drüber geschaut hat. Bei Packagist ist jetzt auch alles aktuell.

**Comment by Kakifrucht** [comment]
:+1:
